/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.application;

import org.junit.Test;

import static java.lang.StringTemplate.STR;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void appHasAGreeting2() {
        String a = "a";
        String b = "b";
        String teste = STR. "\{ a } \{ b }" ;
        assertEquals(teste, "a b");
    }
}
